name: mihoyo_start
description: "A Game Launcher"
publish_to: 'none'
version: 0.1.3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  android_intent_plus: ^5.3.0
  dynamic_color: ^1.1.0
  external_app_launcher: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/    
           